export { default as App } from "./app/App";
export { default as Navbar } from "./navbar/navbar";
export { default as Main } from "./main/main";
export { default as Home } from "./home/home";
export { default as AboutUs } from "./aboutus/aboutus";
export { default as Contact } from "./contact/contact";
export { default as OurDrivers } from "./ourdrivers/ourdrivers";
export { default as OrderRide } from "./orderride/orderride";
export { default as Modal } from "./modal/modal";
